version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo zipping package
      - (cd src; zip -r ../dist.zip *)
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'dist.zip'